version: '2.3'

services:
  loramap:
    build:
      context: .
    image: monicaproject/lora-map:latest
    command: ["dotnet","./Lora-Map.dll"]
    ports:
      - 8080:8080
    volumes:
      - "./config/config:/etc/loramap"
      - "./config/maps:/usr/local/bin/loramap/resources/maps"
      - "./config/json:/usr/local/bin/loramap/json"